filebeat.inputs:

- type: filestream
  id: my-system-logs
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
  tags: ["syslog"]
  
- type: filestream
  id: my-docker-logs
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  parsers:
    - container:
        stream: all
  tags: ["docker"]

#output.kafka:
#  hosts: ["10.0.12.2:9092","10.0.12.3:9092","10.0.12.4:9092"]
#  topic: "kafka-logs"
  
output.logstash:
  hosts: ["IP:5044"] #Если нужно отправлять на несколько IP, то через запятую в кавычки пишутся другие IP
  loadbalance: true

  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/filebeat/certs/logstash.crt"]
  ssl.verification_mode: none
